[Variables]
Scale=1
2412=H
;I H

Player=WNP
NPName=Spotify

Weather=1
Music=1
Animation=1
KeyHook=1
HotKey=LWin Shift

ColorMode=0
MainColor=235, 235, 235
OnColor=0, 118, 205
OffColor=211, 211, 211
OppositeColor=0,0,0

P=40
R=10
GlobalP=10
ShadeW=(450*#scale#)

WeatherLocation=Hong Kong
; Just enter your city's name or your address here or whatever. Anything should work here.
; TIP: Check Rainmeter's log to see what location it got.
WeatherUnits=Metric
; The units of the weather info. Valid values are "Metric" and "Imperial".
Language=en
