[Variables]
@includegVar1=#SKINSPATH##JaxCore\@Resources\gVars\Time.inc
@includegVar2=#SKINSPATH##JaxCore\@Resources\gVars\Weather.inc
@includegVar3=#SKINSPATH##JaxCore\@Resources\gVars\WeatherAPIKey.inc
Scale=1
2412=I
;I H

Player=WNP
NPName=Spotify

Weather=1
Music=1
Animation=0
HideOnFullScreen=1

ColorMode=0
MainColor=34, 34, 36
OnColor=0, 118, 205
OffColor=51, 51, 53
OppositeColor=240,240,240

P=40
R=10
GlobalP=10
ShadeW=(450*#scale#)

WeatherLocation=melbourne
; Just enter your city's name or your address here or whatever. Anything should work here.
; TIP: Check Rainmeter's log to see what location it got.
WeatherUnits=Metric
; The units of the weather info. Valid values are "Metric" and "Imperial".
Language=en

TweenTime1=500
Easing=InOutSine
BlurBool=1
BlurType=Acrylic

Detect.Size=10
ScreenNumber=1
